movieOne:
	VITE_CAPTURESECONDS=0 VITE_CAPTUREON=0 VITE_MOVIENUMBER=1 VITE_MAXPOINTS=10000 npx vite

movieTwo:
	VITE_CAPTURESECONDS=0 VITE_CAPTUREON=0 VITE_MOVIENUMBER=2 VITE_MAXPOINTS=10000 npx vite

movieThree:
	VITE_CAPTURESECONDS=0 VITE_CAPTUREON=0 VITE_MOVIENUMBER=3 VITE_MAXPOINTS=10000 npx vite

movieFour:
	VITE_CAPTURESECONDS=0 VITE_CAPTUREON=0 VITE_MOVIENUMBER=4 VITE_MAXPOINTS=10000 npx vite
